workflows:
  android-apk:
    name: Fundi Mteja Firebase Build
    environment:
      flutter: 3.3.10
      java: 11
    scripts:
      - name: Clean
        script: flutter clean
      - name: Get Packages  
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk