workflows:
  android-apk:
    name: Fundi Mteja APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Clean Project
        script: |
          flutter clean
          rm -rf ~/.pub-cache
          flutter pub get
          flutter pub upgrade
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dulamsamsoni@gmail.com