// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bgEPMtd-JfO0-KWL-4qSXilKNwHXtI',
    appId: '1:93590530060:android:76947b961e812b0db16629',
    messagingSenderId: '93590530060',
    projectId: 'kidafutali-cha-fundi',
    storageBucket: 'kidafutali-cha-fundi.firebasestorage.app',
  );
}