// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bgEPMtd-JfoO-KWL-4qSXIlkNJwHXIk',
    appId: '1:93590530060:android:76947b961e812b0db16629',
    messagingSenderId: '93590530060',
    projectId: 'kidafutali-cha-fundi',
    storageBucket: 'kidafutali-cha-fundi.firebasestorage.app',
    androidClientId: '93590530060-jgchvf6a9ein0cjg4u521212bif5fh4q.apps.googleusercontent.com',
    iosClientId: '93590530060-6a1apgath0rhk8892uuqrmbm4eh2ce1g.apps.googleusercontent.com',
  );
}